var regions = [
  {
    label: "Africa",
    value: "AFRICA",
    timezones: [
      {label: "Central European Standard Time (Ceuta)", value: "Africa/Ceuta"},
      {label: "East Africa Time (Nairobi)", value: "Africa/Nairobi"},
      {label: "Eastern European Standard Time (Cairo)", value: "Africa/Cairo"},
      {label: "Eastern European Standard Time (Tripoli)", value: "Africa/Tripoli"},
      {label: "Greenwich Mean Time (Abidjan)", value: "Africa/Abidjan"},
      {label: "South Africa Standard Time (Johannesburg)", value: "Africa/Johannesburg"},
      {label: "West Africa Standard Time (Lagos)", value: "Africa/Lagos"},
      {label: "West Africa Summer Time (Windhoek)", value: "Africa/Windhoek"},
      {label: "Western European Standard Time (Casablanca)", value: "Africa/Casablanca"}
    ]
  }, {
    label: "Antarctica",
    value: "ANTARCTICA",
    timezones: [
      {label: "Casey Time (Casey)", value: "Antarctica/Casey"},
      {label: "Chile Summer Time (Palmer)", value: "Antarctica/Palmer"},
      {label: "Davis Time (Davis)", value: "Antarctica/Davis"},
      {label: "Dumont-d’Urville Time (Dumont d’Urville)", value: "Antarctica/DumontDUrville"},
      {label: "Greenwich Mean Time (Troll)", value: "Antarctica/Troll"},
      {label: "Macquarie Island Time (Macquarie)", value: "Antarctica/Macquarie"},
      {label: "Mawson Time (Mawson)", value: "Antarctica/Mawson"},
      {label: "New Zealand Daylight Time (McMurdo)", value: "Antarctica/McMurdo"},
      {label: "Rothera Time (Rothera)", value: "Antarctica/Rothera"},
      {label: "Syowa Time (Syowa)", value: "Antarctica/Syowa"},
      {label: "Vostok Time (Vostok)", value: "Antarctica/Vostok"}
    ]
  }, {
    label: "Asia",
    value: "ASIA",
    timezones: [
      {label: "Afghanistan Time (Kabul)", value: "Asia/Kabul"},
      {label: "Arabian Standard Time (Riyadh)", value: "Asia/Riyadh"},
      {label: "Armenia Standard Time (Yerevan)", value: "Asia/Yerevan"},
      {label: "Azerbaijan Standard Time (Baku)", value: "Asia/Baku"},
      {label: "Bangladesh Standard Time (Dhaka)", value: "Asia/Dhaka"},
      {label: "China Standard Time (Shanghai)", value: "Asia/Shanghai"},
      {label: "East Kazakhstan Time (Almaty)", value: "Asia/Almaty"},
      {label: "Eastern European Standard Time (Amman)", value: "Asia/Amman"},
      {label: "Eastern European Standard Time (Beirut)", value: "Asia/Beirut"},
      {label: "Eastern European Standard Time (Damascus)", value: "Asia/Damascus"},
      {label: "Eastern European Standard Time (Gaza)", value: "Asia/Gaza"},
      {label: "Eastern European Standard Time (Hebron)", value: "Asia/Hebron"},
      {label: "Eastern European Standard Time (Nicosia)", value: "Asia/Nicosia"},
      {label: "GMT+03:00 (Istanbul)", value: "Europe/Istanbul"},
      {label: "GMT+08:30 (Pyongyang)", value: "Asia/Pyongyang"},
      {label: "GMT+11:00 (Srednekolymsk)", value: "Asia/Srednekolymsk"},
      {label: "Gulf Standard Time (Dubai)", value: "Asia/Dubai"},
      {label: "Hovd Standard Time (Hovd)", value: "Asia/Hovd"},
      {label: "India Standard Time (Kolkata)", value: "Asia/Calcutta"},
      {label: "Iran Standard Time (Tehran)", value: "Asia/Tehran"},
      {label: "Irkutsk Standard Time (Irkutsk)", value: "Asia/Irkutsk"},
      {label: "Israel Standard Time (Jerusalem)", value: "Asia/Jerusalem"},
      {label: "Japan Standard Time (Tokyo)", value: "Asia/Tokyo"},
      {label: "Krasnoyarsk Standard Time (Krasnoyarsk)", value: "Asia/Krasnoyarsk"},
      {label: "Krasnoyarsk Standard Time (Novokuznetsk)", value: "Asia/Novokuznetsk"},
      {label: "Magadan Standard Time (Magadan)", value: "Asia/Magadan"},
      {label: "Myanmar Time (Rangoon)", value: "Asia/Rangoon"},
      {label: "Nepal Time (Kathmandu)", value: "Asia/Katmandu"},
      {label: "Novosibirsk Standard Time (Novosibirsk)", value: "Asia/Novosibirsk"},
      {label: "Pakistan Standard Time (Karachi)", value: "Asia/Karachi"},
      {label: "Petropavlovsk-Kamchatski Standard Time (Kamchatka)", value: "Asia/Kamchatka"},
      {label: "Ulan Bator Standard Time (Ulaanbaatar)", value: "Asia/Ulaanbaatar"},
      {label: "Uzbekistan Standard Time (Tashkent)", value: "Asia/Tashkent"},
      {label: "Vladivostok Standard Time (Ust-Nera)", value: "Asia/Ust-Nera"},
      {label: "Vladivostok Standard Time (Vladivostok)", value: "Asia/Vladivostok"},
      {label: "Western Indonesia Time (Jakarta)", value: "Asia/Jakarta"},
      {label: "Yakutsk Standard Time (Chita)", value: "Asia/Chita"},
      {label: "Yakutsk Standard Time (Khandyga)", value: "Asia/Khandyga"},
      {label: "Yakutsk Standard Time (Yakutsk)", value: "Asia/Yakutsk"},
      {label: "Yekaterinburg Standard Time (Yekaterinburg)", value: "Asia/Yekaterinburg"}
    ]
  }, {
    label: "Atlantic Ocean",
    value: "ATLANTIC",
    timezones: [
      {label: "Atlantic Daylight Time (Bermuda)", value: "Atlantic/Bermuda"},
      {label: "Azores Standard Time (Azores)", value: "Atlantic/Azores"},
      {label: "Cape Verde Standard Time (Cape Verde)", value: "Atlantic/Cape_Verde"},
      {label: "Falkland Islands Standard Time (Stanley)", value: "Atlantic/Stanley"},
      {label: "Greenwich Mean Time (Reykjavik)", value: "Atlantic/Reykjavik"},
      {label: "South Georgia Time (South Georgia)", value: "Atlantic/South_Georgia"},
      {label: "Western European Standard Time (Canary)", value: "Atlantic/Canary"}
    ],
    label: "Australia",
    value: "AUSTRALIA",
    timezones: [
      {label: "Australian Central Daylight Time (Adelaide)", value: "Australia/Adelaide"},
      {label: "Australian Central Standard Time (Darwin)", value: "Australia/Darwin"},
      {label: "Australian Central Western Standard Time (Eucla)", value: "Australia/Eucla"},
      {label: "Australian Eastern Daylight Time (Sydney)", value: "Australia/Sydney"},
      {label: "Australian Eastern Standard Time (Brisbane)", value: "Australia/Brisbane"},
      {label: "Australian Western Standard Time (Perth)", value: "Australia/Perth"},
      {label: "Lord Howe Daylight Time (Lord Howe)", value: "Australia/Lord_Howe"}
    ]
  }, {
    label: "Europe",
    value: "EUROPE",
    timezones: [
      {label: "Central European Standard Time (Paris)", value: "Europe/Paris"},
      {label: "Eastern European Standard Time (Athens)", value: "Europe/Athens"},
      {label: "Eastern European Standard Time (Chisinau)", value: "Europe/Chisinau"},
      {label: "Eastern European Standard Time (Kaliningrad)", value: "Europe/Kaliningrad"},
      {label: "Eastern European Standard Time (Nicosia)", value: "Asia/Nicosia"},
      {label: "GMT+03:00 (Istanbul)", value: "Europe/Istanbul"},
      {label: "Greenwich Mean Time (London)", value: "Europe/London"},
      {label: "Moscow Standard Time (Minsk)", value: "Europe/Minsk"},
      {label: "Moscow Standard Time (Moscow)", value: "Europe/Moscow"},
      {label: "Moscow Standard Time (Simferopol)", value: "Europe/Simferopol"},
      {label: "Samara Standard Time (Samara)", value: "Europe/Samara"}
    ]
  }, {
    label: "Indian Ocean",
    value: "INDIAN",
    timezones: [
      {label: "Christmas Island Time (Christmas)", value: "Indian/Christmas"},
      {label: "Cocos Islands Time (Cocos)", value: "Indian/Cocos"},
      {label: "East Africa Time (Antananarivo)", value: "Indian/Antananarivo"},
      {label: "Indian Ocean Time (Chagos)", value: "Indian/Chagos"},
      {label: "Maldives Time (Maldives)", value: "Indian/Maldives"},
      {label: "Mauritius Standard Time (Mauritius)", value: "Indian/Mauritius"},
      {label: "Reunion Time (Réunion)", value: "Indian/Reunion"}
    ]
  }, {
    label: "North America",
    value: "NORTH_AMERICA",
    timezones: [
      {label: "Alaska Daylight Time (Anchorage)", value: "America/Anchorage"},
      {label: "Alaska Daylight Time (Metlakatla)", value: "America/Metlakatla"},
      {label: "Atlantic Daylight Time (Goose Bay)", value: "America/Goose_Bay"},
      {label: "Atlantic Daylight Time (Halifax)", value: "America/Halifax"},
      {label: "Atlantic Standard Time (Blanc-Sablon)", value: "America/Blanc-Sablon"},
      {label: "Atlantic Standard Time (Grand Turk)", value: "America/Grand_Turk"},
      {label: "Atlantic Standard Time (Santo Domingo)", value: "America/Santo_Domingo"},
      {label: "Central Daylight Time (Beulah, North Dakota)", value: "America/North_Dakota/Beulah"},
      {label: "Central Daylight Time (Chicago)", value: "America/Chicago"},
      {label: "Central Daylight Time (Matamoros)", value: "America/Matamoros"},
      {label: "Central Standard Time (Bahia Banderas)", value: "America/Bahia_Banderas"},
      {label: "Central Standard Time (Guatemala)", value: "America/Guatemala"},
      {label: "Central Standard Time (Mexico City)", value: "America/Mexico_City"},
      {label: "Cuba Daylight Time (Havana)", value: "America/Havana"},
      {label: "East Greenland Standard Time (Ittoqqortoormiit)", value: "America/Scoresbysund"},
      {label: "Eastern Daylight Time (Nassau)", value: "America/Nassau"},
      {label: "Eastern Daylight Time (New York)", value: "America/New_York"},
      {label: "Eastern Standard Time (Atikokan)", value: "America/Coral_Harbour"},
      {label: "Eastern Standard Time (Cancun)", value: "America/Cancun"},
      {label: "Eastern Standard Time (Panama)", value: "America/Panama"},
      {label: "Eastern Standard Time (Port-au-Prince)", value: "America/Port-au-Prince"},
      {label: "Greenwich Mean Time (Danmarkshavn)", value: "America/Danmarkshavn"},
      {label: "Hawaii-Aleutian Daylight Time (Adak)", value: "America/Adak"},
      {label: "Hawaii-Aleutian Standard Time (Honolulu)", value: "Pacific/Honolulu"},
      {label: "Mexican Pacific Standard Time (Chihuahua)", value: "America/Chihuahua"},
      {label: "Mountain Daylight Time (Denver)", value: "America/Denver"},
      {label: "Mountain Daylight Time (Ojinaga)", value: "America/Ojinaga"},
      {label: "Mountain Standard Time (Fort Nelson)", value: "America/Fort_Nelson"},
      {label: "Mountain Standard Time (Phoenix)", value: "America/Phoenix"},
      {label: "Newfoundland Daylight Time (St. John’s)", value: "America/St_Johns"},
      {label: "Pacific Daylight Time (Los Angeles)", value: "America/Los_Angeles"},
      {label: "Pacific Daylight Time (Tijuana)", value: "America/Tijuana"},
      {label: "St. Pierre &amp; Miquelon Daylight Time (Miquelon)", value: "America/Miquelon"},
      {label: "West Greenland Standard Time (Nuuk)", value: "America/Godthab"}
    ]
  }, {
    label: "Pacific Ocean",
    value: "PACIFIC",
    timezones: [
      {label: "Apia Daylight Time (Apia)", value: "Pacific/Apia"},
      {label: "Chamorro Standard Time (Guam)", value: "Pacific/Guam"},
      {label: "Chatham Daylight Time (Chatham)", value: "Pacific/Chatham"},
      {label: "Easter Island Summer Time (Easter)", value: "Pacific/Easter"},
      {label: "Fiji Standard Time (Fiji)", value: "Pacific/Fiji"},
      {label: "Galapagos Time (Galapagos)", value: "Pacific/Galapagos"},
      {label: "Gambier Time (Gambier)", value: "Pacific/Gambier"},
      {label: "Gilbert Islands Time (Tarawa)", value: "Pacific/Tarawa"},
      {label: "GMT+11:00 (Bougainville)", value: "Pacific/Bougainville"},
      {label: "Hawaii-Aleutian Standard Time (Honolulu)", value: "Pacific/Honolulu"},
      {label: "Line Islands Time (Kiritimati)", value: "Pacific/Kiritimati"},
      {label: "Marquesas Time (Marquesas)", value: "Pacific/Marquesas"},
      {label: "New Caledonia Standard Time (Noumea)", value: "Pacific/Noumea"},
      {label: "New Zealand Daylight Time (Auckland)", value: "Pacific/Auckland"},
      {label: "Norfolk Island Time (Norfolk)", value: "Pacific/Norfolk"},
      {label: "Palau Time (Palau)", value: "Pacific/Palau"},
      {label: "Pitcairn Time (Pitcairn)", value: "Pacific/Pitcairn"},
      {label: "Samoa Standard Time (Pago Pago)", value: "Pacific/Pago_Pago"},
      {label: "Tokelau Time (Fakaofo)", value: "Pacific/Fakaofo"},
      {label: "Tonga Standard Time (Tongatapu)", value: "Pacific/Tongatapu"}
    ]
  }, {
    label: "South America",
    value: "SOUTH_AMERICA",
    timezones: [
      {label: "Acre Standard Time (Rio Branco)", value: "America/Rio_Branco"},
      {label: "Amazon Standard Time (Campo Grande)", value: "America/Campo_Grande"},
      {label: "Argentina Standard Time (Buenos Aires)", value: "America/Buenos_Aires"},
      {label: "Atlantic Standard Time (Grand Turk)", value: "America/Grand_Turk"},
      {label: "Atlantic Standard Time (Santo Domingo)", value: "America/Santo_Domingo"},
      {label: "Bolivia Time (La Paz)", value: "America/La_Paz"},
      {label: "Brasilia Standard Time (Araguaina)", value: "America/Araguaina"},
      {label: "Brasilia Standard Time (Bahia)", value: "America/Bahia"},
      {label: "Brasilia Standard Time (Fortaleza)", value: "America/Fortaleza"},
      {label: "Brasilia Standard Time (Sao Paulo)", value: "America/Sao_Paulo"},
      {label: "Chile Summer Time (Santiago)", value: "America/Santiago"},
      {label: "Cuba Daylight Time (Havana)", value: "America/Havana"},
      {label: "Eastern Daylight Time (Nassau)", value: "America/Nassau"},
      {label: "Eastern Standard Time (Panama)", value: "America/Panama"},
      {label: "Eastern Standard Time (Port-au-Prince)", value: "America/Port-au-Prince"},
      {label: "Fernando de Noronha Standard Time (Noronha)", value: "America/Noronha"},
      {label: "Paraguay Summer Time (Asunción)", value: "America/Asuncion"},
      {label: "Peru Standard Time (Lima)", value: "America/Lima"},
      {label: "Uruguay Standard Time (Montevideo)", value: "America/Montevideo"},
      {label: "Venezuela Time (Caracas)", value: "America/Caracas"},
      {label: "Western Argentina Standard Time (San Luis)", value: "America/Argentina/San_Luis"}
    ]
  }, {
    label: "United States",
    value: "US",
    timezones: [
      {label: "Alaska Daylight Time (Anchorage)", value: "America/Anchorage"},
      {label: "Central Daylight Time (Chicago)", value: "America/Chicago"},
      {label: "Eastern Daylight Time (New York)", value: "America/New_York"},
      {label: "Hawaii-Aleutian Daylight Time (Adak)", value: "America/Adak"},
      {label: "Hawaii-Aleutian Standard Time (Honolulu)", value: "Pacific/Honolulu"},
      {label: "Mountain Daylight Time (Denver)", value: "America/Denver"},
      {label: "Mountain Standard Time (Phoenix)", value: "America/Phoenix"},
      {label: "Pacific Daylight Time (Los Angeles)", value: "America/Los_Angeles"}
    ]
  }
];